csv_column_names: [
        "ADULTPRODUCT",
        "ASIN",
        "AUTOGRAPHED",
        "BRAND",
        "BRANDCODE",
        "BROWSECLASSIFICATION_CLASSIFICATIONID",
        "BROWSECLASSIFICATION_DISPLAYNAME",
        "COLOR",
        "COUNTRY_CODE",
        "ITEMCLASSIFICATION",
        "ITEMNAME",
        "LAST_UPDATED_TIMESTAMP",
        "MANUFACTURER",
        "MANUFACTURERCODE",
        "MANUFACTURERCODEPARENT",
        "MARKETPLACEID",
        "MEMORABILIA",
        "MODELNUMBER",
        "PACKAGEQUANTITY",
        "PARTNUMBER",
        "PRODUCTCATEGORY_DISPLAYNAME",
        "PRODUCTCATEGORY_VALUE",
        "PRODUCTGROUP",
        "PRODUCTSUBCATEGORY_DISPLAYNAME",
        "PRODUCTSUBCATEGORY_VALUE",
        "RELEASEDATE",
        "REPLENISHMENTCATEGORY",
        "SIZE",
        "STYLE",
        "TRADEINELIGIBLE",
        "WEBSITEDISPLAYGROUP",
        "WEBSITEDISPLAYGROUPNAME"
    ]
asin_tables:
  sfSchema: PSA_AMZN_VNDR_CNTRL
