csv_column_names: [
        "AGED90PLUSDAYSSELLABLEINVENTORYCOST",
        "AGED90PLUSDAYSSELLABLEINVENTORYCOST_CURRENCYCODE",
        "AGED90PLUSDAYSSELLABLEINVENTORYUNITS",
        "ASIN",
        "AVERAGEVENDORLEADTIMEDAYS",
        "COUNTRY_CODE",
        "ENDDATE",
        "LAST_UPDATED_TIMESTAMP",
        "NETRECEIVEDINVENTORYCOST",
        "NETRECEIVEDINVENTORYCOST_CURRENCYCODE",
        "NETRECEIVEDINVENTORYUNITS",
        "OPENPURCHASEORDERUNITS",
        "PROCURABLEPRODUCTOUTOFSTOCKRATE",
        "RECEIVEFILLRATE",
        "SELLABLEONHANDINVENTORYCOST",
        "SELLABLEONHANDINVENTORYCOST_CURRENCYCODE",
        "SELLABLEONHANDINVENTORYUNITS",
        "SELLTHROUGHRATE",
        "SOURCEABLEPRODUCTOUTOFSTOCKRATE",
        "STARTDATE",
        "UFT",
        "UNFILLEDCUSTOMERORDEREDUNITS",
        "UNHEALTHYINVENTORYCOST",
        "UNHEALTHYINVENTORYCOST_CURRENCYCODE",
        "UNHEALTHYINVENTORYUNITS",
        "UNSELLABLEONHANDINVENTORYCOST",
        "UNSELLABLEONHANDINVENTORYCOST_CURRENCYCODE",
        "UNSELLABLEONHANDINVENTORYUNITS",
        "VENDORCONFIRMATIONRATE"
    ]
create_report_option:
  data_by_asin_key: inventoryByAsin
  reportType: GET_VENDOR_INVENTORY_REPORT
  reportOptions:
    reportPeriod: WEEK
    sellingProgram: RETAIL
    distributorView: MANUFACTURING
