name: "CHC Ecommerce SB ad group report"
adProduct: "SPONSORED_BRANDS"
groupBy:
  - "adGroup"
columns:
  - "addToCart"
  - "addToCartClicks"
  - "addToCartRate"
  - "adGroupId"
  - "adGroupName"
  - "adStatus"
  - "brandedSearches"
  - "brandedSearchesClicks"
  - "campaignBudgetAmount"
  - "campaignBudgetCurrencyCode"
  - "campaignBudgetType"
  - "campaignId"
  - "campaignName"
  - "campaignStatus"
  - "clicks"
  - "cost"
  - "costType"
  - "date"
  - "detailPageViews"
  - "detailPageViewsClicks"
  - "eCPAddToCart"
  - "impressions"
  - "newToBrandDetailPageViewRate"
  - "newToBrandDetailPageViews"
  - "newToBrandDetailPageViewsClicks"
  - "newToBrandECPDetailPageView"
  - "newToBrandPurchases"
  - "newToBrandPurchasesClicks"
  - "newToBrandPurchasesPercentage"
  - "newToBrandPurchasesRate"
  - "newToBrandSales"
  - "newToBrandSalesClicks"
  - "newToBrandSalesPercentage"
  - "newToBrandUnitsSold"
  - "newToBrandUnitsSoldClicks"
  - "newToBrandUnitsSoldPercentage"
  - "purchases"
  - "purchasesClicks"
  - "purchasesPromoted"
  - "sales"
  - "salesClicks"
  - "salesPromoted"
  - "unitsSold"
  - "unitsSoldClicks"
  - "video5SecondViewRate"
  - "video5SecondViews"
  - "videoCompleteViews"
  - "videoFirstQuartileViews"
  - "videoMidpointViews"
  - "videoThirdQuartileViews"
  - "videoUnmutes"
  - "viewabilityRate"
reportTypeId: "sbAdGroup"
timeUnit: "DAILY"
format: "GZIP_JSON"