name: "Ecommerce SB placement report"
adProduct: "SPONSORED_BRANDS"
groupBy:
  - "campaignPlacement"
columns:
- "date"
- "newToBrandSalesClicks"
- "viewabilityRate"
- "purchasesClicks"
- "detailPageViews"
- "placementClassification"
- "newToBrandSalesPercentage"
- "unitsSold"
- "sales"
- "qualifiedBorrowsFromClicks"
- "addToListFromClicks"
- "costType"
- "campaignStatus"
- "viewClickThroughRate"
- "campaignBudgetAmount"
- "royaltyQualifiedBorrowsFromClicks"
- "purchasesPromoted"
- "newToBrandDetailPageViewRate"
- "purchases"
- "campaignId"
- "newToBrandPurchasesPercentage"
- "qualifiedBorrows"
- "salesPromoted"
- "campaignBudgetCurrencyCode"
- "videoCompleteViews"
- "salesClicks"
- "videoFirstQuartileViews"
- "newToBrandPurchasesRate"
- "unitsSoldClicks"
- "brandedSearches"
- "video5SecondViews"
- "royaltyQualifiedBorrows"
- "newToBrandECPDetailPageView"
- "newToBrandPurchases"
- "brandedSearchesClicks"
- "addToList"
- "newToBrandSales"
- "newToBrandPurchasesClicks"
- "campaignBudgetType"
- "addToCartClicks"
- "videoUnmutes"
- "addToCart"
- "videoThirdQuartileViews"
- "addToCartRate"
- "cost"
- "newToBrandDetailPageViewsClicks"
- "impressions"
- "newToBrandUnitsSold"
- "viewableImpressions"
- "detailPageViewsClicks"
- "eCPAddToCart"
- "newToBrandDetailPageViews"
- "clicks"
- "videoMidpointViews"
- "video5SecondViewRate"
- "newToBrandUnitsSoldClicks"
- "newToBrandUnitsSoldPercentage"
- "campaignName"
reportTypeId: "sbCampaignPlacement"
timeUnit: "DAILY"
format: "GZIP_JSON"