name: "Ecommerce SB purchased product campaigns report"
adProduct: "SPONSORED_BRANDS"
groupBy:
  - "purchasedAsin"
columns:
  - "adGroupId"
  - "adGroupName"
  - "attributionType"
  - "campaignBudgetCurrencyCode"
  - "campaignId"
  - "campaignName"
  - "campaignPriceTypeCode"
  - "date"
  - "newToBrandPurchases14d"
  - "newToBrandPurchasesPercentage14d"
  - "newToBrandSales14d"
  - "newToBrandSalesPercentage14d"
  - "newToBrandUnitsSold14d"
  - "newToBrandUnitsSoldPercentage14d"
  - "orders14d"
  - "ordersClicks14d"
  - "productCategory"
  - "productName"
  - "purchasedAsin"
  - "sales14d"
  - "salesClicks14d"
  - "unitsSold14d"
  - "unitsSoldClicks14d"
reportTypeId: "sbPurchasedProduct"
timeUnit: "DAILY"
format: "GZIP_JSON" 