name: "Ecommerce SB targeting report"
adProduct: "SPONSORED_BRANDS"
groupBy:
  - "targeting"
columns:
  - "addToCart"
  - "addToCartClicks"
  - "addToCartRate"
  - "adGroupId"
  - "adGroupName"
  - "addToList"
  - "addToListFromClicks"
  - "qualifiedBorrows"
  - "qualifiedBorrowsFromClicks"
  - "royaltyQualifiedBorrows"
  - "royaltyQualifiedBorrowsFromClicks"
  - "brandedSearches"
  - "brandedSearchesClicks"
  - "campaignBudgetAmount"
  - "campaignBudgetCurrencyCode"
  - "campaignBudgetType"
  - "campaignId"
  - "campaignName"
  - "campaignStatus"
  - "clicks"
  - "cost"
  - "costType"
  - "date"
  - "detailPageViews"
  - "detailPageViewsClicks"
  - "eCPAddToCart"
  - "impressions"
  - "keywordBid"
  - "keywordId"
  - "adKeywordStatus"
  - "keywordText"
  - "keywordType"
  - "matchType"
  - "newToBrandDetailPageViewRate"
  - "newToBrandDetailPageViews"
  - "newToBrandDetailPageViewsClicks"
  - "newToBrandECPDetailPageView"
  - "newToBrandPurchases"
  - "newToBrandPurchasesClicks"
  - "newToBrandPurchasesPercentage"
  - "newToBrandPurchasesRate"
  - "newToBrandSales"
  - "newToBrandSalesClicks"
  - "newToBrandSalesPercentage"
  - "newToBrandUnitsSold"
  - "newToBrandUnitsSoldClicks"
  - "newToBrandUnitsSoldPercentage"
  - "purchases"
  - "purchasesClicks"
  - "purchasesPromoted"
  - "sales"
  - "salesClicks"
  - "salesPromoted"
  - "targetingExpression"
  - "targetingId"
  - "targetingText"
  - "targetingType"
  - "topOfSearchImpressionShare"
  - "unitsSold"
reportTypeId: "sbTargeting"
timeUnit: "DAILY"
format: "GZIP_JSON"