name: "Ecommerce SD advertised product campaigns report"
adProduct: "SPONSORED_DISPLAY"
groupBy:
  - "advertiser"
columns:
  - "addToCart"
  - "addToCartRate"
  - "addToCartViews"
  - "addToCartClicks"
  - "adGroupId"
  - "adGroupName"
  - "adId"
  - "addToList"
  - "addToListFromClicks"
  - "qualifiedBorrows"
  - "royaltyQualifiedBorrows"
  - "addToListFromViews"
  - "qualifiedBorrowsFromClicks"
  - "qualifiedBorrowsFromViews"
  - "royaltyQualifiedBorrowsFromClicks"
  - "royaltyQualifiedBorrowsFromViews"
  - "bidOptimization"
  - "brandedSearches"
  - "brandedSearchesClicks"
  - "brandedSearchesViews"
  - "brandedSearchRate"
  - "campaignBudgetCurrencyCode"
  - "campaignId"
  - "campaignName"
  - "clicks"
  - "cost"
  - "cumulativeReach"
  - "date"
  - "detailPageViews"
  - "detailPageViewsClicks"
  - "eCPAddToCart"
  - "eCPBrandSearch"
  - "impressions"
  - "impressionsFrequencyAverage"
  - "impressionsViews"
  - "newToBrandDetailPageViewClicks"
  - "newToBrandDetailPageViewRate"
  - "newToBrandDetailPageViews"
  - "newToBrandDetailPageViewViews"
  - "newToBrandECPDetailPageView"
  - "newToBrandPurchases"
  - "newToBrandPurchasesClicks"
  - "newToBrandSales"
  - "newToBrandSalesClicks"
  - "newToBrandUnitsSold"
  - "newToBrandUnitsSoldClicks"
  - "promotedAsin"
  - "promotedSku"
  - "purchases"
  - "purchasesClicks"
  - "purchasesPromotedClicks"
  - "sales"
  - "salesClicks"
  - "salesPromotedClicks"
  - "unitsSold"
  - "unitsSoldClicks"
  - "videoCompleteViews"
  - "videoFirstQuartileViews"
  - "videoMidpointViews"
  - "videoThirdQuartileViews"
  - "videoUnmutes"
  - "viewabilityRate"
  - "viewClickThroughRate"
reportTypeId: "sdAdvertisedProduct"
timeUnit: "DAILY"
format: "GZIP_JSON"