name: "Ecommerce SD campaigns report"
adProduct: "SPONSORED_DISPLAY"
groupBy:
  - "campaign"
columns:
  - "addToCart"
  - "addToCartClicks"
  - "addToCartRate"
  - "addToCartViews"
  - "brandedSearches"
  - "brandedSearchesClicks"
  - "brandedSearchesViews"
  - "brandedSearchRate"
  - "campaignBudgetAmount"
  - "campaignBudgetCurrencyCode"
  - "campaignId"
  - "campaignName"
  - "campaignStatus"
  - "clicks"
  - "cost"
  - "costType"
  - "cumulativeReach"
  - "date"
  - "detailPageViews"
  - "detailPageViewsClicks"
  - "eCPAddToCart"
  - "eCPBrandSearch"
  - "impressions"
  - "impressionsFrequencyAverage"
  - "impressionsViews"
  - "leadFormOpens"
  - "leads"
  - "linkOuts"
  - "longTermROAS"
  - "longTermSales"
  - "newToBrandDetailPageViews"
  - "newToBrandDetailPageViewClicks"
  - "newToBrandDetailPageViewRate"
  - "newToBrandDetailPageViewViews"
  - "newToBrandECPDetailPageView"
  - "newToBrandPurchases"
  - "newToBrandPurchasesClicks"
  - "newToBrandSales"
  - "newToBrandSalesClicks"
  - "newToBrandUnitsSold"
  - "newToBrandUnitsSoldClicks"
  - "purchases"
  - "purchasesClicks"
  - "purchasesPromotedClicks"
  - "sales"
  - "salesClicks"
  - "salesPromotedClicks"
  - "unitsSold"
  - "unitsSoldClicks"
  - "videoCompleteViews"
  - "videoFirstQuartileViews"
  - "videoMidpointViews"
  - "videoThirdQuartileViews"
  - "videoUnmutes"
  - "viewabilityRate"
  - "viewClickThroughRate"
reportTypeId: "sdCampaigns"
timeUnit: "DAILY"
format: "GZIP_JSON" 