name: "Ecommerce SP advertised product campaigns report"
adProduct: "SPONSORED_PRODUCTS"
groupBy:
  - "advertiser"
columns:
  - "acosClicks14d"
  - "acosClicks7d"
  - "adGroupId"
  - "adGroupName"
  - "adId"
  - "advertisedAsin"
  - "advertisedSku"
  - "attributedSalesSameSku14d"
  - "attributedSalesSameSku1d"
  - "attributedSalesSameSku30d"
  - "attributedSalesSameSku7d"
  - "campaignBudgetAmount"
  - "campaignBudgetCurrencyCode"
  - "campaignBudgetType"
  - "campaignId"
  - "campaignName"
  - "campaignStatus"
  - "clickThroughRate"
  - "clicks"
  - "cost"
  - "costPerClick"
  - "date"
  - "impressions"
  - "kindleEditionNormalizedPagesRead14d"
  - "kindleEditionNormalizedPagesRoyalties14d"
  - "portfolioId"
  - "purchases14d"
  - "purchases1d"
  - "purchases30d"
  - "purchases7d"
  - "purchasesSameSku14d"
  - "purchasesSameSku1d"
  - "purchasesSameSku30d"
  - "purchasesSameSku7d"
  - "roasClicks14d"
  - "roasClicks7d"
  - "sales14d"
  - "sales1d"
  - "sales30d"
  - "sales7d"
  - "salesOtherSku7d"
  - "spend"
  - "unitsSoldClicks14d"
  - "unitsSoldClicks1d"
  - "unitsSoldClicks30d"
  - "unitsSoldClicks7d"
  - "unitsSoldOtherSku7d"
  - "unitsSoldSameSku14d"
  - "unitsSoldSameSku1d"
  - "unitsSoldSameSku30d"
  - "unitsSoldSameSku7d"    
reportTypeId: "spAdvertisedProduct"
timeUnit: "DAILY"
format: "GZIP_JSON"