name: "Ecommerce SP campaigns report"
adProduct: "SPONSORED_PRODUCTS"
groupBy:
  - "campaign"
columns:
  - "attributedSalesSameSku1d"
  - "attributedSalesSameSku14d"
  - "attributedSalesSameSku30d"
  - "attributedSalesSameSku7d"
  - "campaignBiddingStrategy"
  - "clickThroughRate"
  - "clicks"
  - "cost"
  - "costPerClick"
  - "date"
  - "impressions"
  - "kindleEditionNormalizedPagesRead14d"
  - "kindleEditionNormalizedPagesRoyalties14d"
  - "purchases1d"
  - "purchases14d"
  - "purchases30d"
  - "purchases7d"
  - "purchasesSameSku1d"
  - "purchasesSameSku14d"
  - "purchasesSameSku30d"
  - "purchasesSameSku7d"
  - "sales1d"
  - "sales14d"
  - "sales30d"
  - "sales7d"
  - "spend"
  - "unitsSoldClicks1d"
  - "unitsSoldClicks14d"
  - "unitsSoldClicks30d"
  - "unitsSoldClicks7d"
  - "unitsSoldSameSku1d"
  - "unitsSoldSameSku14d"
  - "unitsSoldSameSku30d"
  - "unitsSoldSameSku7d"
  - "campaignName"
  - "campaignId"
  - "campaignStatus"
  - "campaignBudgetAmount"
  - "campaignBudgetType"
  - "campaignRuleBasedBudgetAmount"
  - "campaignApplicableBudgetRuleId"
  - "campaignApplicableBudgetRuleName"
  - "campaignBudgetCurrencyCode"
  - "topOfSearchImpressionShare"
reportTypeId: "spCampaigns"
timeUnit: "DAILY" 
format: "GZIP_JSON"