name: "CHC Ecommerce SP purchased product report"
adProduct: "SPONSORED_PRODUCTS"
groupBy:
  - "asin"
columns:
  - "adGroupId"
  - "adGroupName"
  - "advertisedAsin"
  - "advertisedSku"
  - "campaignBudgetCurrencyCode"
  - "campaignId"
  - "campaignName"
  - "date"
  - "keyword"
  - "keywordId"
  - "keywordType"
  - "kindleEditionNormalizedPagesRead14d"
  - "kindleEditionNormalizedPagesRoyalties14d"
  - "matchType"
  - "portfolioId"
  - "purchasedAsin"
  - "purchases1d"
  - "purchases7d"
  - "purchases14d"
  - "purchases30d"
  - "purchasesOtherSku1d"
  - "purchasesOtherSku7d"
  - "purchasesOtherSku14d"
  - "purchasesOtherSku30d"
  - "sales1d"
  - "sales7d"
  - "sales14d"
  - "sales30d"
  - "salesOtherSku1d"
  - "salesOtherSku7d"
  - "salesOtherSku14d"
  - "salesOtherSku30d"
  - "unitsSoldClicks1d"
  - "unitsSoldClicks7d"
  - "unitsSoldClicks14d"
  - "unitsSoldClicks30d"
  - "unitsSoldOtherSku1d"
  - "unitsSoldOtherSku7d"
  - "unitsSoldOtherSku14d"
  - "unitsSoldOtherSku30d"
reportTypeId: "spPurchasedProduct"
timeUnit: "DAILY"
format: "GZIP_JSON" 