name: "Ecommerce SP targeting report"
adProduct: "SPONSORED_PRODUCTS"
groupBy:
  - "targeting"
columns:
  - "impressions"
  - "addToList"
  - "qualifiedBorrows"
  - "royaltyQualifiedBorrows"
  - "clicks"
  - "costPerClick"
  - "clickThroughRate"
  - "cost"
  - "purchases1d"
  - "purchases7d"
  - "purchases14d"
  - "purchases30d"
  - "purchasesSameSku1d"
  - "purchasesSameSku7d"
  - "purchasesSameSku14d"
  - "purchasesSameSku30d"
  - "unitsSoldClicks1d"
  - "unitsSoldClicks7d"
  - "unitsSoldClicks14d"
  - "unitsSoldClicks30d"
  - "sales1d"
  - "sales7d"
  - "sales14d"
  - "sales30d"
  - "attributedSalesSameSku1d"
  - "attributedSalesSameSku7d"
  - "attributedSalesSameSku14d"
  - "attributedSalesSameSku30d"
  - "unitsSoldSameSku1d"
  - "unitsSoldSameSku7d"
  - "unitsSoldSameSku14d"
  - "unitsSoldSameSku30d"
  - "kindleEditionNormalizedPagesRead14d"
  - "kindleEditionNormalizedPagesRoyalties14d"
  - "salesOtherSku7d"
  - "unitsSoldOtherSku7d"
  - "acosClicks7d"
  - "acosClicks14d"
  - "roasClicks7d"
  - "roasClicks14d"
  - "keywordId"
  - "keyword"
  - "campaignBudgetCurrencyCode"
  - "date"
  - "portfolioId"
  - "campaignName"
  - "campaignId"
  - "campaignBudgetType"
  - "campaignBudgetAmount"
  - "campaignStatus"
  - "keywordBid"
  - "adGroupName"
  - "adGroupId"
  - "adKeywordStatus"
  - "keywordType"
  - "matchType"
  - "targeting"
  - "topOfSearchImpressionShare"
reportTypeId: "spTargeting"
timeUnit: "DAILY"
format: "GZIP_JSON"