name : "campaign_LTV"
query : "WITH campaign_list AS (
       SELECT
              advertiser,
              entity_id AS ad_en_id,
              currency_iso_code,
              campaign,
              campaign_id_string,
              creative,
              ad_product_type
       FROM
              sponsored_ads_traffic
       GROUP BY
              advertiser,
              entity_id,
              currency_iso_code,
              campaign,
              campaign_id_string,
              creative,
              ad_product_type
),
brand_campaign_lookup AS (
       SELECT
              max(
                     CASE
                            WHEN LOWER(advertiser) LIKE '%allegra%' THEN 'Allegra'
                            WHEN LOWER(creative) LIKE '%allegra%' THEN 'Allegra'
                            WHEN LOWER(campaign) LIKE '%allegra%' THEN 'Allegra'
                            WHEN LOWER(advertiser) LIKE '%aspercreme%' THEN 'Aspercreme'
                            WHEN LOWER(creative) LIKE '%aspercreme%' THEN 'Aspercreme'
                            WHEN LOWER(campaign) LIKE '%aspercreme%' THEN 'Aspercreme'
                            WHEN LOWER(advertiser) LIKE '%cortizone%' THEN 'Cortizone 10'
                            WHEN LOWER(creative) LIKE '%cortizone%' THEN 'Cortizone 10'
                            WHEN LOWER(campaign) LIKE '%cortizone%' THEN 'Cortizone 10'
                            WHEN LOWER(advertiser) LIKE '%dulcolax%' THEN 'Dulcolax'
                            WHEN LOWER(creative) LIKE '%dulcolax%' THEN 'Dulcolax'
                            WHEN LOWER(campaign) LIKE '%dulcolax%' THEN 'Dulcolax'
                            WHEN LOWER(advertiser) LIKE '%gold bond%' THEN 'Gold Bond'
                            WHEN LOWER(creative) LIKE '%gold bond%' THEN 'Gold Bond'
                            WHEN LOWER(campaign) LIKE '%gold bond%' THEN 'Gold Bond'
                            WHEN LOWER(advertiser) LIKE '%icy hot%' THEN 'Icy Hot'
                            WHEN LOWER(creative) LIKE '%icy hot%' THEN 'Icy Hot'
                            WHEN LOWER(campaign) LIKE '%icy hot%' THEN 'Icy Hot'
                            WHEN LOWER(advertiser) LIKE '%nasacort%' THEN 'Nasacort'
                            WHEN LOWER(creative) LIKE '%nasacort%' THEN 'Nasacort'
                            WHEN LOWER(campaign) LIKE '%nasacort%' THEN 'Nasacort'
                            WHEN LOWER(advertiser) LIKE '%selsun blue%' THEN 'Selsun Blue'
                            WHEN LOWER(creative) LIKE '%selsun blue%' THEN 'Selsun Blue'
                            WHEN LOWER(campaign) LIKE '%selsun blue%' THEN 'Selsun Blue'
                            WHEN LOWER(advertiser) LIKE '%unisom%' THEN 'Unisom'
                            WHEN LOWER(creative) LIKE '%unisom%' THEN 'Unisom'
                            WHEN LOWER(campaign) LIKE '%unisom%' THEN 'Unisom'
                            WHEN LOWER(advertiser) LIKE '%xyzal%' THEN 'Xyzal'
                            WHEN LOWER(creative) LIKE '%xyzal%' THEN 'Xyzal'
                            WHEN LOWER(campaign) LIKE '%xyzal%' THEN 'Xyzal'
                            WHEN LOWER(advertiser) LIKE '%zantac%' THEN 'Zantac'
                            WHEN LOWER(creative) LIKE '%zantac%' THEN 'Zantac'
                            WHEN LOWER(campaign) LIKE '%zantac%' THEN 'Zantac'
                            WHEN LOWER(advertiser) LIKE '%pharmaton%' THEN 'Pharmaton'
                            WHEN LOWER(creative) LIKE '%pharmaton%' THEN 'Pharmaton'
                            WHEN LOWER(campaign) LIKE '%pharmaton%' THEN 'Pharmaton'
                            WHEN LOWER(advertiser) LIKE '%initiv%' THEN 'Initiv'
                            WHEN LOWER(creative) LIKE '%initiv%' THEN 'Initiv'
                            WHEN LOWER(campaign) LIKE '%initiv%' THEN 'Initiv'
                            WHEN LOWER(advertiser) LIKE '%dulcosoft%' THEN 'Dulcoease'
                            WHEN LOWER(creative) LIKE '%dulcosoft%' THEN 'Dulcoease'
                            WHEN LOWER(campaign) LIKE '%dulcosoft%' THEN 'Dulcoease'
                            WHEN LOWER(advertiser) LIKE '%pton%' THEN 'PTON'
                            WHEN LOWER(creative) LIKE '%pton%' THEN 'PTON'
                            WHEN LOWER(campaign) LIKE '%pton%' THEN 'PTON'
                            WHEN LOWER(advertiser) LIKE '%bisolherbal%' THEN 'Bisolherbal'
                            WHEN LOWER(creative) LIKE '%bisolherbal%' THEN 'Bisolherbal'
                            WHEN LOWER(campaign) LIKE '%bisolherbal%' THEN 'Bisolherbal'
                            WHEN LOWER(advertiser) LIKE '%buscomint%' THEN 'Buscomint'
                            WHEN LOWER(creative) LIKE '%buscomint%' THEN 'Buscomint'
                            WHEN LOWER(campaign) LIKE '%buscomint%' THEN 'Buscomint'
                            WHEN LOWER(advertiser) LIKE '%allevia%' THEN 'Allevia'
                            WHEN LOWER(creative) LIKE '%allevia%' THEN 'Allevia'
                            WHEN LOWER(campaign) LIKE '%allevia%' THEN 'Allevia'
                            WHEN LOWER(advertiser) LIKE '%buscopan%' THEN 'Buscopan'
                            WHEN LOWER(creative) LIKE '%buscopan%' THEN 'Buscopan'
                            WHEN LOWER(campaign) LIKE '%buscopan%' THEN 'Buscopan'
                            WHEN LOWER(advertiser) LIKE '%dulcoease%' THEN 'Dulcoease'
                            WHEN LOWER(creative) LIKE '%dulcoease%' THEN 'Dulcoease'
                            WHEN LOWER(campaign) LIKE '%dulcoease%' THEN 'Dulcoease'
                            WHEN LOWER(advertiser) LIKE '%act%' THEN 'ACT'
                            WHEN LOWER(creative) LIKE '%act%' THEN 'ACT'
                            WHEN LOWER(campaign) LIKE '%act%' THEN 'ACT'
                            ELSE 'UNCLASSIFIED'
                     END
              ) AS brand,
              advertiser,
              currency_iso_code,
              campaign,
              campaign_id_string,
              ad_product_type
       FROM
              campaign_list
       GROUP BY
              advertiser,
              currency_iso_code,
              campaign,
              campaign_id_string,
              ad_product_type
),
sponsored_ads AS (
       SELECT
              sat.campaign,
              sat.campaign_id_string,
              uc.ad_product_type,
              sat.advertiser,
              uc.brand,
              advertiser_timezone,
              uc.currency_iso_code,
              campaign_start_date,
              campaign_end_date,
              user_id,
              impressions AS impressions,
              spend,
              clicks,
              0 AS detail_page_view,
              0 AS brand_halo_detail_page_view,
              0 AS total_detail_page_view,
              0 AS purchases,
              0 AS brand_halo_purchases,
              0 AS total_purchases,
              0 AS product_sales,
              0 AS brand_halo_product_sales,
              0 AS total_product_sales,
              0 AS units_sold,
              0 AS brand_halo_units_sold,
              0 AS total_units_sold,
              0 AS new_to_brand_purchases,
              0 AS new_to_brand_brand_halo_purchases,
              0 AS new_to_brand_total_purchases,
              0 AS interactions_count,
              0 AS new_to_brand_product_sales,
              0 AS new_to_brand_total_product_sales,
              0 AS new_to_brand_brand_halo_product_sales
       FROM
              sponsored_ads_traffic sat
              JOIN brand_campaign_lookup uc ON sat.campaign_id_string = uc.campaign_id_string
       WHERE
              user_id IS NOT NULL
),
attributed_conversions AS (
       SELECT
              aae.campaign,
              aae.campaign_id_string,
              CASE
                     WHEN aae.ad_product_type IS NULL THEN 'DSP'
                     ELSE aae.ad_product_type
              END AS ad_product_type,
              aae.advertiser,
              uc.brand,
              advertiser_timezone,
              uc.currency_iso_code,
              campaign_start_date,
              campaign_end_date,
              user_id,
              0 AS impressions,
              0 AS cost,
              0 AS clicks,
              0 AS total_cost,
              sum(detail_page_view) AS detail_page_view,
              sum(brand_halo_detail_page_view) AS brand_halo_detail_page_view,
              sum(total_detail_page_view) AS total_detail_page_view,
              sum(purchases) AS purchases,
              sum(brand_halo_purchases) AS brand_halo_purchases,
              sum(total_purchases) AS total_purchases,
              sum(product_sales) AS product_sales,
              sum(brand_halo_product_sales) AS brand_halo_product_sales,
              sum(total_product_sales) AS total_product_sales,
              sum(units_sold) AS units_sold,
              sum(brand_halo_units_sold) AS brand_halo_units_sold,
              sum(total_units_sold) AS total_units_sold,
              sum(new_to_brand_purchases) AS new_to_brand_purchases,
              sum(new_to_brand_brand_halo_purchases) AS new_to_brand_brand_halo_purchases,
              sum(new_to_brand_total_purchases) AS new_to_brand_total_purchases,
              sum(new_to_brand_product_sales) AS  new_to_brand_product_sales, 
              sum(new_to_brand_total_product_sales) AS new_to_brand_total_product_sales,
              sum(new_to_brand_brand_halo_product_sales) AS new_to_brand_brand_halo_product_sales, 
              sum(
                     case
                            when total_purchases > 0 then 1
                            else 0
                     end
              ) interactions_count
       FROM
              amazon_attributed_events_by_traffic_time aae
              JOIN brand_campaign_lookup uc ON aae.campaign_id_string = uc.campaign_id_string
       WHERE
              user_id IS NOT NULL
       GROUP BY
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10
),
combined_info AS (
       SELECT
              campaign,
              campaign_id_string,
              ad_product_type,
              advertiser,
              brand,
              advertiser_timezone,
              currency_iso_code,
              campaign_start_date,
              campaign_end_date,
              user_id,
              impressions,
              spend,
              0 AS total_cost,
              clicks,
              detail_page_view,
              brand_halo_detail_page_view,
              total_detail_page_view,
              purchases,
              brand_halo_purchases,
              total_purchases,
              product_sales,
              brand_halo_product_sales,
              total_product_sales,
              units_sold,
              brand_halo_units_sold,
              total_units_sold,
              new_to_brand_purchases,
              new_to_brand_brand_halo_purchases,
              new_to_brand_total_purchases,
              new_to_brand_product_sales,
              new_to_brand_total_product_sales,
              new_to_brand_brand_halo_product_sales,
              interactions_count
       FROM
              sponsored_ads
       UNION
       ALL
       SELECT
              campaign,
              campaign_id_string,
              ad_product_type,
              advertiser,
              brand,
              advertiser_timezone,
              currency_iso_code,
              campaign_start_date,
              campaign_end_date,
              user_id,
              impressions,
              0 AS spend,
              0 AS total_cost,
              clicks,
              detail_page_view,
              brand_halo_detail_page_view,
              total_detail_page_view,
              purchases,
              brand_halo_purchases,
              total_purchases,
              product_sales,
              brand_halo_product_sales,
              total_product_sales,
              units_sold,
              brand_halo_units_sold,
              total_units_sold,
              new_to_brand_purchases,
              new_to_brand_brand_halo_purchases,
              new_to_brand_total_purchases,
              new_to_brand_product_sales,
              new_to_brand_total_product_sales,
              new_to_brand_brand_halo_product_sales,
              interactions_count
       FROM
              attributed_conversions
),
camp_start AS (
       SELECT
              campaign_id_string,
              min(campaign_start_date_utc) campaign_start_date_utc,
              max(campaign_end_date_utc) campaign_end_date_utc
       FROM
              sponsored_ads_traffic
       group by
              1
)
SELECT
       built_in_parameter('TIME_WINDOW_START') AS time_window_start,
       built_in_parameter('TIME_WINDOW_END') AS time_window_end,
       ci.brand,
       ci.campaign,
       ci.campaign_id_string,
       ci.currency_iso_code,
       CASE
              WHEN ad_product_type = 'DSP' THEN 'DSP'
              WHEN ad_product_type = 'sponsored_products' THEN 'SP'
              WHEN ad_product_type = 'sponsored_display' THEN 'SD'
              WHEN ad_product_type = 'sponsored_brands' THEN 'SB'
              ELSE 'undefined_ad_type'
       END AS ad_product_type,
       sum(spend / 100000000)  AS cost_sum,
       sum(impressions) AS impressions_sum,
       sum(clicks) AS clicks_sum,
       count(DISTINCT ci.user_id) AS reach,
       sum(detail_page_view) AS detail_page_view_sum,
       sum(brand_halo_detail_page_view) AS brand_halo_detail_page_view_sum,
       sum(total_detail_page_view) AS total_detail_page_view_sum,
       sum(purchases) AS purchases_sum,
       sum(brand_halo_purchases) AS brand_halo_purchases_sum,
       sum(total_purchases) AS total_purchases_sum,
       sum(product_sales) AS product_sales_sum,
       sum(brand_halo_product_sales) AS brand_halo_product_sales_sum,
       sum(total_product_sales) AS total_product_sales_sum,
       sum(units_sold) AS units_sold_sum,
       sum(brand_halo_units_sold) AS brand_halo_units_sold_sum,
       sum(total_units_sold) AS total_units_sold_sum,
       sum(new_to_brand_purchases) AS new_to_brand_purchases_sum,
       sum(new_to_brand_brand_halo_purchases) AS new_to_brand_brand_halo_purchases_sum,
       sum(new_to_brand_total_purchases) AS new_to_brand_total_purchases_sum,
       SUM(new_to_brand_product_sales) AS new_to_brand_product_sales_sum,
       SUM(new_to_brand_total_product_sales) AS new_to_brand_total_product_sales_sum,
       SUM(new_to_brand_brand_halo_product_sales) AS new_to_brand_brand_halo_product_sales_sum,
       count(
              distinct case
                     when ci.total_purchases > 0 then ci.user_id
                     else null
              end
       ) AS shoppers_num,
       sum(interactions_count) AS total_orders_count,
       min(cs.campaign_start_date_utc) AS campaign_start_date_utc,
       max(cs.campaign_end_date_utc) AS campaign_end_date_utc
FROM
       combined_info ci
       LEFT JOIN camp_start cs ON ci.campaign_id_string = cs.campaign_id_string
GROUP BY
       1,
       2,
       3,
       4,
       5,
       6,
       7" 