country_code:
  US:
    api_urls:
      report_url: "https://advertising-api.amazon.com"
      profile_fetch: "https://advertising-api.amazon.com/v2/profiles"
      access_token_generation: "https://api.amazon.com/auth/o2/token"

    marketPlaceIds: "ATVPDKIKX0DER"
    instance_id: "amcj68hxinz"
    timeWindowType: "EXPLICIT"
    entity_id: "ENTITY1NFDZEZI3ZVXM"
    content_type: "application/json"

  ES:
    api_urls:
      report_url: "https://advertising-api.amazon.com"
      access_token_generation: "https://api.amazon.com/auth/o2/token"

    marketPlaceIds: "ATVPDKIKX0DER"
    instance_id: "amcbakzbbhu"
    timeWindowType: "EXPLICIT"
    entity_id: "ENTITY1NFDZEZI3ZVXM"
    content_type: "application/json"

  GB:
    api_urls:
      report_url: "https://advertising-api.amazon.com"
      profile_fetch: "https://advertising-api-eu.amazon.com/v2/profiles"
      access_token_generation: "https://api.amazon.com/auth/o2/token"
      
    marketPlaceIds: "ATVPDKIKX0DER"
    instance_id: "amclvqsws1q"
    timeWindowType: "EXPLICIT"
    entity_id: "ENTITY1NFDZEZI3ZVXM"
    content_type: "application/json"

destination_output_path: "de/amc/{country_code}/{report_type}/{report_type}_{day}{month}{year}.csv"

reports:
  overlap_ads: "overlap_ads.yml"
  path_purchase: "path_to_purchase.yml"
  campaign_ltv: "campaign_LTV.yml"
  sns: "sns.yml"